import crypto from 'node:crypto';
import { authenticator } from 'otplib';
import QRCode from 'qrcode';
import { sha256 } from './crypto';

/**
 * TOTP (RFC 6238) for opt-in two-factor authentication.
 *
 * Mirrors services/verification.ts in spirit — this is the second factor's
 * equivalent of the email OTP — but the two are NOT interchangeable:
 * VerificationCode holds short-lived (10 minute), single-issue codes hashed with
 * a plain sha256; a TOTP secret is long-lived and must be REVERSIBLE (the server
 * recomputes the code on every check), so it is encrypted at rest via
 * encryptField/decryptField (services/encryption.ts) rather than hashed. That
 * encrypt/decrypt happens at the controller call sites, not in here — this file
 * only ever sees the plaintext secret.
 *
 * otplib is pinned to 12.0.1, not the current major (13.x installs by default).
 * v13 replaced the `authenticator` singleton with a plugin-based `TOTP` class and
 * dropped `keyuri`/`generateSecret` from that surface entirely — a breaking
 * rewrite, not a patch. 12.x is the last release with the classic
 * `authenticator.generateSecret/keyuri/verify` API this module is written
 * against, and it is still RFC 6238-correct; only the plugin architecture around
 * it changed upstream.
 *
 * `authenticator.options` is set ONCE at module load, not per call: the
 * instance is a shared singleton, and otplib has no per-call options argument
 * on `generate`/`check` in this version. Setting it here rather than scattering
 * `{ window: 1 }` at each call site keeps the drift tolerance in one place.
 */
authenticator.options = {
  // Accept the code one 30s step behind or ahead of "now", so a phone whose
  // clock has drifted slightly — or a code typed just as the window rolled
  // over — still verifies. This is otplib's own recommended default; it does
  // NOT widen the guessing surface the way it might look like it does, because
  // consumeScopedBudget still caps attempts at the controller layer regardless
  // of how many of the ~3 valid codes a single guess could land on.
  window: 1,
};

const ISSUER = '4КУБ CRM';

/** A fresh base32 TOTP secret, generated by otplib (backed by node's crypto RNG). */
export function generateTotpSecret(): string {
  return authenticator.generateSecret();
}

/** The otpauth:// URI an authenticator app scans or imports. */
export function buildOtpauthUrl(secret: string, accountLabel: string): string {
  return authenticator.keyuri(accountLabel, ISSUER, secret);
}

/** PNG QR code of the otpauth URL above, as a data: URL the client can render directly. */
export async function generateQrCodeDataUrl(otpauthUrl: string): Promise<string> {
  return QRCode.toDataURL(otpauthUrl);
}

/**
 * Does this 6-digit code match the secret right now (± one 30s step — see the
 * module-level `authenticator.options` above)?
 *
 * Never throws: a malformed token (wrong length, non-numeric) is simply not a
 * match, exactly like a wrong-but-well-formed one — callers should not have to
 * distinguish "invalid code" from "code that failed to parse".
 */
export function verifyTotpToken(secret: string, token: string): boolean {
  try {
    return authenticator.check(token, secret);
  } catch {
    return false;
  }
}

/**
 * Unambiguous alphabet for backup codes: base32 (A-Z2-7) with the characters
 * that are easy to misread on a screenshot or a hand-copied note removed —
 * 0/O and 1/I. 32 symbols, so each character carries exactly 5 bits and
 * `randomAlphabetChar` can reject-sample a byte cleanly.
 */
const BACKUP_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

/**
 * One unbiased character from BACKUP_CODE_ALPHABET, via crypto.randomBytes and
 * rejection sampling rather than `Math.random() * alphabet.length` — the latter
 * is neither cryptographically strong nor uniform (a JS float's precision does
 * not divide evenly by 32), and this is a credential, not a UI shuffle.
 */
function randomAlphabetChar(): string {
  const alphabetSize = BACKUP_CODE_ALPHABET.length;
  const maxUnbiased = 256 - (256 % alphabetSize);
  let byte: number;
  do {
    byte = crypto.randomBytes(1)[0];
  } while (byte >= maxUnbiased);
  return BACKUP_CODE_ALPHABET[byte % alphabetSize];
}

/**
 * `count` single-use backup codes, plaintext, formatted XXXX-XXXX (8 alphabet
 * characters plus a separator for readability). Shown to the caller exactly
 * once at generation time — only hashBackupCode's output is ever persisted.
 */
export function generateBackupCodes(count = 10): string[] {
  const codes: string[] = [];
  for (let i = 0; i < count; i += 1) {
    let raw = '';
    for (let j = 0; j < 8; j += 1) {
      raw += randomAlphabetChar();
    }
    codes.push(`${raw.slice(0, 4)}-${raw.slice(4)}`);
  }
  return codes;
}

/**
 * Deterministic digest of a backup code, for storage and for matching a
 * submitted code against TotpBackupCode.code_hash.
 *
 * Normalizes first (trim, uppercase, strip anything that is not an alphabet
 * character — i.e. the separator) so `abcd-1234`-shaped user input compares
 * equal to the canonical `ABCD-1234` form regardless of how it was typed or
 * pasted, while staying a no-op on an already-canonical code. Reuses sha256
 * from ./crypto — the same digest verification.ts hashes email OTP codes
 * with — rather than a second hashing primitive for the same job.
 */
export function hashBackupCode(code: string): string {
  const normalized = code.trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
  return sha256(normalized);
}
